typography_spectrum: 0.29708574898540974
color:
  brandStrength: 0.31718283193185925
  lightness: 0.6422189415898174
  saturation: 0.16807251330465078
  rhythmicContrast: 0.303940340410918
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
layout_spectrum: 0.30682836426422
author:
  name: Ebo Eppenga
  email: ebo@eppenga.com
  url: 'http://ebo.eppen.ga/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0a0c4f89-cfb2-42da-b43c-6da4a516bec0.png
name: Eppenga Grid
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/bb5627fd-1b8a-41f9-ae84-30597692fbcc.png
